default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  url: <%= ENV["DATABASE_URL"] || "postgres://#{ENV.fetch("POSTGRES_USER", "sonaka")}:#{ENV.fetch("POSTGRES_PASSWORD", "sonaka_dev_password")}@#{ENV.fetch("BACKEND_DB_HOST", "postgres")}:#{ENV.fetch("BACKEND_DB_PORT", 5432)}/#{ENV.fetch("POSTGRES_DB", "sonaka_dev")}" %>

development:
  <<: *default

test:
  <<: *default
  url: postgres://sonaka:sonaka_dev_password@postgres:5432/sonaka_test

production:
  <<: *default


